spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 951200
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名和下划线命名映射